package com.utils.novalista;

/**
 * Created by lucas on 29/05/18.
 */

public class HinosData {
    public static final String[] HINOS = {"A BELEZA DA TUA SANTIDADE",
            "A CRISTO COROAI ",
            "A DEUS DEMOS GLÓRIA",
            "A DEUS SEJA O LOUVOR",
            "A DEUS, SUPREMO CRIADOR ",
            "A IGREJA QUE ORA É VITORIOSA",
            "A JESUS IREI LOUVAR",
            "A JESUS SEJA DADA TODA GLÓRIA",
            "A LEI DO SENHOR É PERFEITA",
            "A LUZ DO MUNDO",
            "A MEU SENHOR",
            "A MINH'ALMA ENGRANDECE ",
            "A MINH'ALMA ESTAVA LONGE DO CAMINHO DO CÉU",
            "A MINHA ALEGRIA",
            "A MINHA HERANÇA",
            "A MINHA HERANÇA É O SENHOR",
            "A MINHA VIDA ENTREGO",
            "A MINHA VIDA TÃO VAZIA",
            "A NOIVA AMADA DO CORDEIRO",
            "A NOIVA É A IGREJA",
            "A NOVA DO EVANGELHO",
            "A OBRA DO SENHOR É PERFEITA",
            "A PAZ QUE TU PROCURAS",
            "A TERRA SEMEAMOS ",
            "A TEUS PÉS, JESUS",
            "A TI, QUE HABITAS ENTRE OS QUERUBINS",
            "A TUA JUSTIÇA",
            "A TUA PALAVRA",
            "A TUA PALAVRA É SEMENTE",
            "A ÚLTIMA TROMBETA SOARÁ",
            "A VIDA DE MINH'ALMA",
            "A VIDA NO MUNDO É CRUEL",
            "A VITÓRIA DESTA IGREJA É ORAÇÃO ",
            "ABBA PAI",
            "ABRA A PORTA, VENHA VER! ",
            "ABRE A PORTA DO TEU CORAÇÃO",
            "ACABOU-SE O TEMPO DA DERROTA",
            "ACHEI SALVAÇÃO",
            "ADORAR-TE",
            "ADORAREI",
            "AGRADECIDOS SOMOS A TI",
            "AINDA QUE A FIGUEIRA",
            "AINDA QUE OS SEUS SONHOS ",
            "AINDA UMA VEZ (AGEU) ",
            "ALELUIA (SALMOS 113) ",
            "ALELUIA! MUITAS VOZES DE ANJOS",
            "ALÉM DO CÉU AZUL",
            "ALÉM DO VÉU EU QUERO ESTAR",
            "ALERTA POVO ESTÁ CHEGANDO A NOSSA HORA",
            "ALGEMADO POR UM PESO ",
            "ALMA CANSADA ",
            "AMO AO MEU SENHOR",
            "AMO AO SENHOR",
            "AMO AO SENHOR DE TODO O MEU CORAÇÃO",
            "AMO AO SENHOR PORQUE ELE ME OUVIU",
            "AMOR, QUE POR AMOR DESCESTE!",
            "AO CHEGAR AO CÉU GOZO EU TEREI",
            "AO CORDEIRO",
            "AO DEUS DE ABRAÃO ",
            "AO DEUS DE AMOR E DE IMENSA BONDADE",
            "AO FINDAR O LABOR DESTA VIDA (A ÚLTIMA HORA) ",
            "AO LADO DE DEUS",
            "AO LADO DE JESUS QUERO EU ESTAR ",
            "AO POÇO DE JACÓ CHEGOU JESUS",
            "AO QUE ESTÁ NO TRONO",
            "AO SENTIR O MUNDO AO MEU REDOR ",
            "AO SENTIR O TEU PERDÃO",
            "AQUELE QUE HABITA NO ESCONDERIJO ",
            "AQUELE QUE TEM OS MEUS MANDAMENTOS",
            "ARDENDO EM FOGO MINH'ALMA ESTÁ",
            "ARREBATADO FUI NO DIA DO SENHOR",
            "AS GRUTAS, AS ROCHAS IMENSAS ",
            "AS LÁGRIMAS FALAM, JESUS TE ESCUTA ",
            "AS MUITAS ÁGUAS",
            "AS MUITAS ÁGUAS NÃO PODERIAM APAGAR",
            "AS RIQUEZAS DO MUNDO",
            "AS TUAS MÃOS DIRIGEM MEU DESTINO",
            "ÀS VEZES, ALGUÉM ME PERGUNTA",
            "ASSIM COMO A NOITE ESPERA PELO DIA",
            "ATENDE A VOZ DO MEU CLAMOR",
            "ATENDE, SENHOR, A MINHA ORAÇÃO",
            "ATUA EM NOSSO MEIO",
            "AVANTE, AVANTE, Ó CRENTES ",
            "BASTA DIZERES O QUE QUERES",
            "BASTA QUE ME TOQUES, SENHOR",
            "BEM DE MANHÃ, EMBORA O CÉU SERENO",
            "BEM SEI QUE TUDO PODES ",
            "BENDITA A HORA DE ORAÇÃO ",
            "BENDITO SEJA O CORDEIRO",
            "BENDIZE, Ó MINH'ALMA , AO SENHOR",
            "BENDIZEI AO SENHOR",
            "BOM É LOUVAR AO SENHOR",
            "BOM É O SENHOR",
            "BREVE NO CÉU JESUS HÁ DE APARECER",
            "BREVE VOLTARÁ O MESSIAS",
            "BRILHE SOBRE MIM",
            "BUSCAR-ME-EIS ",
            "BUSCOU-ME COM TERNURA",
            "CADA DIA ME DIRIGE ",
            "CADA DIA QUE EU VEJO O SOL",
            "CADA INSTANTE",
            "CADA PASSO QUE DÁS ",
            "CAMINHANDO VOU PARA CANAÃ ",
            "CANTA ALEGREMENTE, Ó FILHA DE SIÃO",
            "CANTAI ALEGREMENTE A DEUS",
            "CANTAI AO SENHOR UM CÂNTICO NOVO",
            "CANTAI, Ó IGREJA",
            "CANTAREI A BONDADE E A JUSTIÇA",
            "CANTAREI A MISERICÓRDIA",
            "CANTAREI AO AMOR DOS AMORES",
            "CANTAREI AO MEU SENHOR ENQUANTO EU VIVER",
            "CANTAREI, CANTAREI AS MISERICÓRDIAS",
            "CANTAREI, CANTAREI HOSANA",
            "CAREÇO DE JESUS! ",
            "CASTELO FORTE",
            "CELEBRAI COM JÚBILO AO SENHOR",
            "CERTA VEZ EU ORANDO",
            "CERTA VEZ, AO ORAR",
            "CERTO HOMEM TÃO NOBRE",
            "CHEGADO A CRUZ DO MEU SALVADOR ",
            "CHEGOU O TEMPO DE PENSAR",
            "CHEGUEMOS AO ALTAR DE DEUS",
            "CHUVAS DE BÊNÇÃOS TEREMOS",
            "CLAMANDO ESTOU",
            "CLAMAREI, CLAMAREI",
            "CLAMO A TI",
            "CLAMO, Ó SENHOR, PELO SANGUE DE JESUS",
            "CLAMO, Ó SENHOR, POR TEU SANGUE",
            "COM A MINHA VOZ CLAMO AO SENHOR ",
            "COM CRISTO NO BARCO",
            "COM TUA MÃO SEGURA BEM A MINHA (AMPARO DIVINO)",
            "COMIGO HABITA, Ó DEUS!",
            "COMO A FLOR DO CAMPO",
            "COMO ACONTECEU EM JERUSALÉM (VAMOS BUSCAR PODER)",
            "COMO AS ÁGUAS",
            "COMO CRISTO ENSINOU",
            "COMO DESISTIR DESTE GRANDE AMOR?",
            "COMO É BOM OUVIR TUA VOZ ",
            "COMO É BOM SABER",
            "COMO É BOM SERVIR AO SENHOR",
            "COMO É BOM TE ADORAR",
            "COMO FOI PARA O CÉU, JESUS CRISTO HÁ DE VIR",
            "COMO TU QUERES",
            "COMO UM BOM PASTOR",
            "COMO UMA FOLHA AO VENTO",
            "CONFIA E ORA ",
            "CONFIO EM DEUS",
            "CONFORME A SUA INFINITA GRAÇA",
            "CONSOLA-ME, ESPÍRITO SANTO",
            "CONSOLAI, CONSOLAI O MEU POVO",
            "CONTA PRA JESUS ONDE É A TUA DOR ",
            "CORDEIRO ETERNO",
            "COROAI ",
            "CORTARAM O MADEIRO",
            "CRIA EM MIM, Ó DEUS",
            "CRISTO CAMINHAVA EM DIREÇÃO À CRUZ",
            "CRISTO CAMINHAVA LENTAMENTE",
            "CRISTO É A RESPOSTA",
            "CRISTO É A ROSA MAIS BELA",
            "CRISTO É MEU AMIGO, É MEU AMIGO",
            "CRISTO É MEU, SIM, CRISTO É MEU",
            "CRISTO É O SENHOR",
            "CRISTO É TUDO PARA MIM",
            "CRISTO É VITÓRIA",
            "CRISTO JÁ NOS PREPAROU",
            "CRISTO JÁ RESSUSCITOU",
            "CRISTO JESUS É O MEU BOM SALVADOR",
            "CRISTO ME DARÁ",
            "CRISTO PODE HOJE VIR (OH! DIA ALEGRE!) ",
            "CRISTO SENTE AMOR POR MIM",
            "CRISTO VEM ME BUSCAR",
            "CRISTO, MEU BOM MESTRE",
            "CRISTO, MEU MESTRE, SEMPRE HÁ DE AMAR-ME",
            "CRISTO, NOME MAIS ALTO",
            "CRUCIFICADO FOI MEU JESUS",
            "DA IGREJA O FUNDAMENTO É CRISTO (PEDRA FUNDAMENTAL)",
            "DA LINDA PÁTRIA",
            "DÁ-ME MAIS FÉ",
            "DAI GLÓRIA A DEUS ",
            "DAS MARAVILHAS QUE A BÍBLIA CONTÉM",
            "DAS PROFUNDEZAS",
            "DAS PROFUNDEZAS A TI CLAMO, Ó SENHOR",
            "DAS PROFUNDEZAS CLAMO A TI, Ó SENHOR!",
            "DE MADRUGADA EU BUSCO A FACE DO SENHOR",
            "DEIXA A GLÓRIA DE DEUS BRILHAR",
            "DEIXA DEUS FALAR AO TEU CORAÇÃO",
            "DEIXA-ME CHORAR",
            "DEIXOU O ESPLENDOR DE SUA GLÓRIA",
            "DELEITA-TE TAMBÉM NO SENHOR",
            "DEPENDO DE TI, SENHOR",
            "DERRAMAREI MEU ESPÍRITO",
            "DESCEU DA SUA GLÓRIA",
            "DESDE O DIA EM QUE TE CONHECI",
            "DESEJEI ARDENTEMENTE",
            "DESFAÇO AS TUAS TRANSGRESSÕES",
            "DESTE MUNDO ESCRAVO FUI (GRANDES COISAS FEZ O SENHOR POR NÓS)",
            "DEUS AMOU O MUNDO DE TAL MANEIRA",
            "DEUS CONHECE A TUA VIDA",
            "DEUS CRIOU OS CÉUS E A TERRA",
            "DEUS CUIDA DE TI",
            "DEUS DA MINHA SALVAÇÃO",
            "DEUS DOS ANTIGOS",
            "DEUS DOS EXÉRCITOS DE ISRAEL",
            "DEUS É CONTIGO",
            "DEUS É MINHA ROCHA ",
            "DEUS É NOSSO AMPARO, NOSSA FORTALEZA",
            "DEUS É NOSSO AUXÍLIO",
            "DEUS ENVIOU SEU FILHO AMADO",
            "DEUS ENVIOU SEU FILHO PRA NOS SALVAR",
            "DEUS ESTÁ AQUI",
            "DEUS ESTÁ NO TEMPLO",
            "DEUS ESTÁ PRESENTE AQUI NESTE LUGAR",
            "DEUS ESTÁ PRESENTE ENTRE PECADORES COMO NÓS",
            "DEUS ESTÁ PRESENTE SEMPRE PRONTO A NOS AJUDAR",
            "DEUS FALOU COMIGO",
            "DEUS FORTE COMO JEOVÁ",
            "DEUS HABITA NO MEIO DOS LOUVORES",
            "DEUS HOJE QUER TE FALAR",
            "DEUS O SEU FILHO ENVIOU",
            "DEUS PROVERÁ",
            "DEUS TE GUARDARÁ",
            "DEUS VOS GUARDE PELO SEU PODER ",
            "DIANTE DE TI",
            "DIGNO É JESUS",
            "DIRIGE-ME, SENHOR",
            "DISPÕE-TE, RESPLANDECE",
            "DIVINO COMPANHEIRO",
            "DO CÉU VIRÁ ",
            "DO NORTE VEM O ÁUREO ESPLENDOR",
            "DO PÃO DO CÉU",
            "DOIS DISCÍPULOS NO CAMINHO DE EMAÚS",
            "DONS DO ESPÍRITO SANTO",
            "DORMINDO NO MEU LEITO",
            "É BASTANTE PARA MIM A TUA GRAÇA",
            "É BOM, É BOM DEMAIS",
            "É DEUS QUEM NOS TEM DADO A VITÓRIA",
            "É JESUS DAS CRIANCINHAS",
            "É O AMOR DE DEUS",
            "É PRECISO CONFIAR E BUSCAR A DEUS",
            "É SOMENTE TEU MEU CORAÇÃO",
            "É TÃO TRISTE NÃO VER A LUZ",
            "É TEMPO, É TEMPO",
            "É TEU SANGUE",
            "EIS A ESCRAVA RESGATADA",
            "EIS AÍ O DIA ACEITÁVEL",
            "EIS MARCHAMOS PARA AQUELE BOM PAÍS",
            "EIS MENSAGEM DO SENHOR",
            "EIS O CORDEIRO DE DEUS",
            "EIS O ESTANDARTE",
            "EIS OS MILHÕES ",
            "EIS QUE ABRO A PORTA ",
            "EIS QUE ESTOU À PORTA",
            "EIS QUE ESTOU À PORTA E BATO",
            "EIS QUE JESUS VEM NAS NUVENS",
            "EIS QUE SURGE UM POVO FORTE",
            "EIS-ME AQUI, SENHOR, EM TEU ALTAR",
            "ELE É A MINHA ALEGRIA ",
            "ELE É A RAIZ",
            "ELE É A ROSA DE SAROM",
            "ELE É O REI DOS REIS",
            "ELE UM DIA ME CHAMOU",
            "ELE UM DIA VOLTARÁ",
            "ELE VIVE EM MIM",
            "ELE VOLTARÁ PRA BUSCAR A SUA IGREJA",
            "ELE VOLTARÁ, SIM, ELE VOLTARÁ",
            "EM BREVE ESCUTAREI",
            "EM BREVE O DIA CHEGARÁ",
            "EM BREVE, MUI BREVE",
            "EM FERVENTE ORAÇÃO",
            "EM ME VINDO O TEMOR",
            "EM MEU CORAÇÃO",
            "EM NADA PONHO A MINHA FÉ",
            "EM NOSSOS LÁBIOS",
            "EM TEU ALTAR, SENHOR",
            "EM TEU NOME",
            "EM TI EU ENCONTRO, Ó DEUS, TODA PAZ",
            "EM TUA PRESENÇA ENTRAMOS",
            "EM TUAS MÃOS, SENHOR",
            "EM TUAS PISADAS",
            "ENCONTREI O GRANDE AMOR",
            "ENQUANTO, Ó SALVADOR, TEU LIVRO LER ",
            "ENTREGA O TEU CAMINHO",
            "ENTREGA O TEU CAMINHO AO SENHOR",
            "ENTREI NO TEMPO DE DEUS",
            "ENTRONIZADO ESTÁ ENTRE AS NAÇÕES",
            "ENVIA A TUA LUZ",
            "ERA UM PECADOR, ANDAVA SEM JESUS",
            "ERA UMA OLIVEIRA",
            "ERAM CEM OVELHAS",
            "ÉS MAJESTADE",
            "ÉS O MAIS FORMOSO, JESUS",
            "ÉS O PÃO DA VIDA",
            "ESCUTA-ME, SENHOR",
            "ESFORÇA-TE, TEM BOM ÂNIMO!",
            "ESPERA NO SENHOR, ANIMA-TE",
            "ESPEREI CONFIANTEMENTE NO SENHOR",
            "ESPÍRITO DO TRINO DEUS",
            "ESPÍRITO SANTO, Ó CONSOLADOR",
            "ESTA ALEGRIA NÃO VAI MAIS SAIR",
            "ESTA CANÇÃO",
            "ESTA É A VOZ, A VOZ DO MEU AMADO",
            "ESTA OBRA É DE DEUS ",
            "ESTA PAZ QUE SINTO EM MINH'ALMA",
            "ESTAMOS AQUI, Ó DEUS",
            "ESTE MUNDO JAMAIS PODE ME SEPARAR",
            "ESTE MUNDO NÃO TEM A SUA PAZ",
            "ESTENDE TUA MÃO",
            "ESTEVÃO AVISTOU (EU TAMBÉM QUERO VER) ",
            "ESTOU A CAMINHAR",
            "ESTOU ALEGRE",
            "ESTOU AQUI PRA CONFESSAR",
            "ESTOU CONFIANDO",
            "EU ABRI MEU CORAÇÃO",
            "EU AVISTO UMA TERRA FELIZ",
            "EU CONFIO EM TI, SENHOR ",
            "EU DESCI PARA O VALE DE BÊNÇÃO E PAZ",
            "EU ESPERO, ANSIOSO, POR MEU DEUS",
            "EU ESTAVA SÓ, SEM O SENHOR",
            "EU LOUVAREI, EU LOUVAREI",
            "EU ME LEMBRO QUANDO JESUS ME TOCOU",
            "EU ME PROSTRO EM TEU ALTAR",
            "EU NÃO SABERIA CAMINHAR",
            "EU NÃO SEI QUAL SERÁ MEU LOUVOR ",
            "EU OUVI DA FORMOSA CIDADE",
            "EU PERDIDO PECADOR ",
            "EU QUERO ANDAR SEMPRE COM JESUS",
            "EU QUERO CANTAR",
            "EU QUERO CANTAR DE GOZO E DE PAZ",
            "EU QUERO MAIS E MAIS DE CRISTO ",
            "EU QUERO SENTIR",
            "EU QUERO SER O SAL DA TERRA",
            "EU QUERO SER, SENHOR AMADO",
            "EU SEI QUE JESUS",
            "EU SIRVO UM DEUS ",
            "EU SÓ QUERO SER, SENHOR",
            "EU SOU DO MEU AMADO E ELE ME TEM AFEIÇÃO",
            "EU SOU FELIZ PORQUE TENHO UM DEUS QUE ME AMA",
            "EU SOU POBRE E NECESSITADO",
            "EU SOU TÃO FELIZ COM O MEU JESUS",
            "EU SOU UMA OVELHINHA",
            "EU TE AMO, MEU JESUS",
            "EU TENHO UM AMIGO",
            "EU TENHO UM DEUS MUI, MUI, MUI GRANDE",
            "EU TENHO UM TESOURO",
            "EU TUDO POSSO NAQUELE QUE ME FORTALECE",
            "EU VENHO A TI, SENHOR",
            "EU VENHO DIZER",
            "EU VEREI A ÁRVORE DA VIDA",
            "EU VI O SENHOR",
            "EU VIM AQUI, SENHOR",
            "EU VOU CONTAR UMA HISTÓRIA",
            "EXALTAI AO SENHOR",
            "EXALTAI, EXALTAI",
            "EXISTE UM ALGUÉM QUE CUIDA DE MIM",
            "EXISTE UM LAR",
            "FALA AO MEU CORAÇÃO, JESUS",
            "FALA, JESUS QUERIDO",
            "FAZ-ME INABALÁVEL",
            "FAZE ORAÇÃO",
            "FELICIDADE É TER CRISTO AO MEU LADO",
            "FELIZ, FELIZ EU SOU",
            "FINDA A LIDA TERREAL",
            "FIRME NAS PROMESSAS",
            "FLUA EM MIM, SENHOR",
            "FLUIRÁ COMO UM RIO",
            "FONTE DA VIDA",
            "FONTE DE ÁGUAS VIVAS",
            "GLÓRIA E ALELUIA",
            "GLÓRIA PRA SEMPRE AO CORDEIRO DE DEUS",
            "GLÓRIA, GLÓRIA",
            "GLORIOSO ÉS, JESUS",
            "GRAÇAS DOU, Ó SENHOR ",
            "GRANDE AMOR, Ó GRANDE AMOR ",
            "GRANDE DEUS, ÚNICO DEUS",
            "GRANDE É O SENHOR",
            "GRANDE É O SENHOR E MUI DIGNO DE SER LOUVADO",
            "GRANDE TESOURO ABERTO É A BÍBLIA",
            "GRANDES SÃO, SENHOR, OS TEUS FEITOS (GRATIDÃO) ",
            "GRANDIOSO PARA MIM",
            "GUIA, Ó CRISTO, A MINHA NAU ",
            "HÁ ALGUÉM QUE CUIDA DE TI",
            "HÁ HOJE ALGUÉM ESPERANDO",
            "HÁ MOMENTOS QUE AS PALAVRAS NÃO RESOLVEM",
            "HÁ SEMPRE ALGUÉM QUE NÃO PROVOU",
            "HÁ TANTA TERRA",
            "HÁ UM AMIGO SEMPRE JUNTO",
            "HÁ UM DOCE ESPÍRITO AQUI",
            "HÁ UM LINDO PAÍS",
            "HÁ UM LUGAR PRA MIM",
            "HÁ UM NOME QUE RELUZ",
            "HÁ UM POVO QUE TE ADORA",
            "HÁ UM RIO DE ÁGUAS VIVAS",
            "HÁ UM SER QUE VIVE EM MIM",
            "HÁ UM SÓ QUE É DIGNO",
            "HÁ UMA FONTE ABERTA NO CALVÁRIO",
            "HÁ UMA LINDA CANÇÃO DE AMOR",
            "HÁ UMA LINDA MORADA",
            "HÁ UMA LUZ A BRILHAR",
            "HÁ UMA OBRA QUE DEUS QUER FAZER",
            "HÁ VITÓRIA PARA MIM",
            "HÁ VITÓRIA SEMPRE EM TI, SENHOR",
            "HAVEREMOS DE CHEGAR",
            "HOJE EU NÃO QUERO PEDIR",
            "HOJE O SENHOR DERRAMOU",
            "HOJE QUERO SOMENTE AGRADECER ",
            "HOJE SEI, SENHOR",
            "HOSANA AO FILHO DE DAVI",
            "IGREJA, CORPO DE CRISTO",
            "IGREJA, TU VAIS SUBIR",
            "INSTRUMENTO EM TUAS MÃOS",
            "INVOCA-ME E TE RESPONDEREI",
            "IREI CANTAR E ADORAR O REI JESUS",
            "ISRAEL SAIU DO EGITO",
            "JÁ ACHEI UMA FLOR GLORIOSA",
            "JÁ CHEGUEI ATÉ AQUI (VITÓRIAS) ",
            "JÁ NÃO ESTOU SOZINHO",
            "JÁ NÃO TARDA O AMANHECER",
            "JÁ REFULGE A GLÓRIA ETERNA ",
            "JERUSALÉM ANSEIO VER",
            "JERUSALÉM ETERNA",
            "JERUSALÉM EXCELSA",
            "JERUSALÉM, CIDADE DO MEU REI",
            "JERUSALÉM, JERUSALÉM",
            "JERUSALÉM, SUAS RUAS DE OURO",
            "JESUS CRISTO É O CAMINHO",
            "JESUS CRISTO MUDOU MEU VIVER",
            "JESUS CRISTO VOLTARÁ",
            "JESUS CRISTO VOLTARÁ COM SEU GRANDE ESPLENDOR",
            "JESUS CRISTO, REI DOS REIS",
            "JESUS DEUS SANTO, SANTO, SANTO! ",
            "JESUS É A ROCHA INABALÁVEL",
            "JESUS É MELHOR, SIM, QUE OURO E BENS",
            "JESUS É O AMIGO MELHOR",
            "JESUS É O CAMINHO",
            "JESUS É O CORDEIRO",
            "JESUS É TUDO PRA MIM ",
            "JESUS ESTÁ ÀS PORTAS",
            "JESUS FEZ A PROMESSA",
            "JESUS IA CAMINHANDO (CANTA MEU POVO) ",
            "JESUS IA SEGUINDO",
            "JESUS IA SUBINDO O MONTE",
            "JESUS LIBERTOU",
            "JESUS ME AMA",
            "JESUS TÃO BELO",
            "JESUS TOMOU O MEU FARDO",
            "JESUS VÊ A SUA IGREJA",
            "JESUS VEIO E SALVOU-ME",
            "JESUS VEM! VEM NOS BUSCAR!",
            "JESUS VIU A MULTIDÃO",
            "JESUS, A LUZ DIVINA",
            "JESUS, A MINH'ALMA TEM SEDE DE TI",
            "JESUS, AGORA EU BEM SEI",
            "JESUS, EM TUA PRESENÇA",
            "JESUS, EU TE AMO E MUITO",
            "JESUS, JESUS, EU TE AMO",
            "JESUS, NOME PRECIOSO",
            "JESUS, O LÍRIO DOS VALES",
            "JESUS, Ó MEU JESUS",
            "JESUS, O QUE MAIS QUERO NESSE MUNDO ",
            "JESUS, QUANDO ME LEMBRO",
            "JESUS, QUERO AMAR-TE",
            "JESUS, SENHOR, ME CHEGO A TI",
            "JESUS, SIM, VEM, DO CÉU EM GLÓRIA ELE VEM",
            "JESUS, TE ENTRONIZAMOS",
            "JESUS, TE ENTRONIZAMOS AQUI ENTRE NÓS",
            "JESUS, TU ÉS O MEU DEUS",
            "JESUS, VEM ME ABENÇOAR",
            "JUNTO A TI SUPLICO, Ó PAI",
            "JUNTO AO TRONO DE DEUS, PREPARADO",
            "JUSTO ÉS, SENHOR",
            "LÁ ESTÁ O MEU TESOURO ",
            "LÁ NO CÉU OS ANJOS CANTAM",
            "LÁ NO CÉU TODOS CANTAM ALELUIA! ",
            "LÁ NO CIMO DO MONTE",
            "LÁ NO DOCE PORVIR",
            "LÁ ONDE EU NÃO POSSO VER (A ORAÇÃO) ",
            "LÂMPADA PARA OS MEUS PÉS",
            "LEVA TU CONTIGO O NOME",
            "LEVANTAI-VOS, Ó PORTAIS ETERNOS",
            "LINDO! LINDO! LINDO!",
            "LOGO DE MANHÃ ",
            "LOUVADO SEJA O NOME DO SENHOR",
            "LOUVAI A JESUS",
            "LOUVAI AO SENHOR PORQUE ELE É BOM",
            "LOUVAI AO SENHOR TODAS AS NAÇÕES",
            "LOUVAI, SERVOS DO SENHOR",
            "LOUVAMOS-TE, Ó DEUS",
            "LOUVANDO A DEUS ",
            "LOUVAREI AO MEU SENHOR",
            "LOUVOR E GLÓRIA",
            "MAIS DO TEU SANTO ESPÍRITO",
            "MAIS PERTO DE JESUS",
            "MAIS PERTO QUERO ESTAR",
            "MAIS UMA VEZ",
            "MAJESTADE, GLÓRIA E MAJESTADE",
            "MANDA FOGO, SENHOR",
            "MANSO E SUAVE JESUS ESTÁ CHAMANDO",
            "MARAVILHA É AMOR DE DEUS",
            "MARAVILHOSA GRAÇA",
            "MARAVILHOSO E SUBLIME PRA MIM",
            "MARAVILHOSO SERÁ",
            "MEDITAREI NAS MARAVILHAS DO SENHOR",
            "MEDO TENS QUE O TENTADOR TE VÁ VENCER?",
            "MESA PREPARADA ",
            "MESTRE O MAR SE REVOLTA ",
            "MEU AMADO FILHO",
            "MEU BARCO É PEQUENO",
            "MEU BOM PASTOR É CRISTO",
            "MEU CAMINHO PONHO EM SUAS MÃOS",
            "MEU CORAÇÃO ENGRANDECE AO SENHOR (CÂNTICO DE VITÓRIA)",
            "MEU DEUS VENCE BATALHAS ",
            "MEU DEUS, MEU BOM PASTOR",
            "MEU DEUS, MEU PAI",
            "MEU LOUVOR É SÓ PRA TI",
            "MEU PECADO RESGATADO",
            "MEU SERVO, NÃO TEMAS",
            "MINH'ALMA TEM SEDE DE TI ",
            "MINHA ALMA, POIS, ALEGRE CANTA ",
            "MINHA DEDICAÇÃO",
            "MINHA PORÇÃO ",
            "MORRI NA CRUZ POR TI",
            "MOTIVOS TENHO PRA LOUVAR-TE",
            "MUITOS ANJOS LOUVAM",
            "MUITOS SÃO OS QUE CONFIAM",
            "NA AREIA NÃO QUERO CONSTRUIR",
            "NA CIDADE DE DAVI NASCEU O SALVADOR",
            "NA ETERNIDADE",
            "NA EXPRESSÃO DESTE LOUVOR",
            "NA HORA EM QUE EU QUISER FALAR COM DEUS",
            "NA NOVA JERUSALÉM IREI MORAR",
            "NA PRESENÇA DE JESUS",
            "NA TERRA ABENÇOADA",
            "NÃO A NÓS, SENHOR",
            "NÃO DESANIMES! DEUS PROVERÁ",
            "NÃO EXISTE OUTRO AMOR IGUAL AO TEU, SENHOR",
            "NÃO HÁ AMOR IGUAL",
            "NÃO HÁ DEUS ACIMA DO SENHOR",
            "NÃO HÁ DEUS TÃO GRANDE COMO TU",
            "NÃO MAIS VIVO EU MAS CRISTO VIVE EM MIM ",
            "NÃO POR FORÇA",
            "NÃO SE TURBEM OS VOSSOS CORAÇÕES",
            "NÃO SEI POR QUE DE DEUS O AMOR",
            "NÃO SEI QUANDO CRISTO JESUS HÁ DE VIR",
            "NÃO SEI SE OUVISTE FALAR",
            "NÃO TEMAS, POIS TE ESCOLHI",
            "NÃO TEREI MAIS TRISTEZAS",
            "NÃO TINHA PARECER",
            "NÃO VAI TARDAR",
            "NAS ESTRELAS VEJO A SUA MÃO",
            "NAS LINDAS MORADAS",
            "NASCEU UM NOVO DIA",
            "NEM SEMPRE ENTENDEMOS",
            "NESTA HORA DE CLAMOR ",
            "NESTA HORA EM ORAÇÃO ",
            "NESTA HORA ESQUEÇO O MUNDO",
            "NESTA NOITE FELIZ",
            "NO CAMINHO ELE ME GUIARÁ",
            "NO CÉU HÁ JANELAS ABERTAS",
            "NO DIA DA GRANDE GLÓRIA ",
            "NO EXPRESSO VIAJAMOS",
            "NO GETSÊMANI",
            "NO MEU CORAÇÃO",
            "NO MEU CORAÇÃO HÁ UM TESOURO",
            "NO PRINCÍPIO ERA O VERBO",
            "NO SERVIÇO DO MEU REI EU SOU FELIZ",
            "NO SILÊNCIO DA NOITE",
            "NO TRONO DA CIDADE DE DEUS",
            "NOS ÁTRIOS DO SENHOR ENTRAMOS",
            "NOS PROSTREMOS AOS SEUS PÉS",
            "NÓS RECEBEREMOS LÁ NO CÉU",
            "NÓS TE ADORAMOS, SENHOR",
            "NÓS VAMOS LÁ, IRMÃOS ",
            "NOSSA GRATIDÃO ",
            "NOSSAS VIDAS SÃO MUDADAS",
            "NOSSO DEUS É SOBERANO",
            "NOSSO LOUVOR",
            "NOVA ALIANÇA",
            "NOVO CAMINHO ",
            "NUNCA MAIS, NUNCA MAIS",
            "Ó AMADO DE MINH'ALMA",
            "O AMOR DE DEUS É GRANDE",
            "O AMOR DE DEUS POR NÓS",
            "O AMOR DE JESUS É GRANDE",
            "O ANJO DO SENHOR ESTÁ PASSEANDO",
            "O CAMINHO QUE NOS LEVA AO CÉU É JESUS",
            "O CÉU É UM LUGAR MARAVILHOSO ",
            "O CORDEIRO QUE NA CRUZ MORREU",
            "O CRIADOR DO UNIVERSO",
            "Ó CRISTO! PÃO DA VIDA",
            "O DEUS A QUEM SERVIMOS",
            "O DIA DO SENHOR VIRÁ",
            "O ESPÍRITO DE DEUS FALA À SUA IGREJA",
            "O ESPÍRITO DO SENHOR ESTÁ SENDO DERRAMADO",
            "O ESTANDARTE DESTA IGREJA",
            "O GRANDE AMOR DO MEU SENHOR ",
            "Ó GRANDE DEUS",
            "O GRANDE DIA ESTÁ CHEGANDO ",
            "O GRANDE RELÓGIO ",
            "Ó JESUS, EXALTAR-TE-EI",
            "Ó JESUS! Ó VERA PÁSCOA",
            "O MESMO DEUS",
            "O MEU AMADO DESCEU AO SEU JARDIM",
            "O MEU AMADO FALA E ME DIZ",
            "O MEU CORAÇÃO",
            "O MEU CORAÇÃO SE REGOZIJA NO SENHOR",
            "O MEU LOUVOR É FRUTO",
            "O MEU VIVER É CRISTO ",
            "O MUNDO NÃO SABE",
            "Ó PAI, EU QUERIA TANTO VER",
            "Ó PASTOR DE ISRAEL",
            "O PODER DO SANGUE DE JESUS",
            "O POVO QUE ANDAVA EM TREVAS",
            "Ó PROFUNDIDADE DAS RIQUEZAS",
            "O QUE HÁ DE VIR, VIRÁ",
            "O QUE HABITA NO ABRIGO DE DEUS",
            "O QUE OS OLHOS NUNCA VIRAM ",
            "O REI E EU",
            "O SANGUE DE JESUS",
            "O SANGUE DE JESUS TEM PODER",
            "O SANGUE DE JESUS TEM PODER PARA SALVAR",
            "O SANGUE DE JESUS, VERTIDO ALI NA CRUZ",
            "O SANGUE DO CORDEIRO DE DEUS",
            "O SENHOR DA CEIFA ESTÁ CHAMANDO",
            "O SENHOR É A ALEGRIA",
            "O SENHOR É A MINHA LUZ",
            "O SENHOR É O MEU PASTOR (SALMO 23)",
            "O SENHOR É O MEU PASTOR (REFRIGERA A MINH'ALMA)",
            "O SENHOR É O MEU PASTOR (BONDADE E MISERICÓRDIA)",
            "O SENHOR É O MEU PASTOR (MINH'ALMA CANTARÁ) ",
            "O SENHOR É O MEU PASTOR (MARANATA, JESUS VEM) ",
            "O SENHOR REINA",
            "O SENHOR TE GUIARÁ",
            "Ó SENHOR, DEUS DE ISRAEL",
            "O SENTIDO DE VIVER",
            "O SOL ESCURECERÁ",
            "O TEU PECADO TU QUERES DEIXAR?",
            "Ó TU QUE HABITAS ENTRE OS QUERUBINS",
            "Ó VEM DERRAMAR",
            "Ó VEM LOGO, JESUS",
            "Ó VINDE ADORAR",
            "Ó VINDE E ADOREMOS ",
            "OH! CONTEMPLAI",
            "OH! PENSAI NESSE LAR LÁ DO CÉU",
            "OH! POR QUE DUVIDAR?",
            "OH! QUANTO ALMEJO ESTAR",
            "OH! QUÃO BOM E QUÃO SUAVE É",
            "OH! QUÃO CEGO ANDEI E PERDIDO VAGUEI",
            "OH! QUE BELOS HINOS HOJE LÁ NO CÉU",
            "OH! QUE PRECIOSO SANGUE",
            "OH! QUE SANGUE PODEROSO",
            "OH! QUE SAUDOSA LEMBRANÇA",
            "OLHAI PARA O ALTO",
            "ONDE ESTÁ O CORDEIRO?",
            "ONDE ESTARIA EU?",
            "ONDE NASCEU JESUS?",
            "ONDE QUER QUE TU FORES IREI, JESUS",
            "ONDE VIVE O REI DA GLÓRIA?",
            "ONIPOTENTE DEUS",
            "ONTEM, HOJE E PARA SEMPRE",
            "OS CÉUS EM BREVE SE ABRIRÃO",
            "OS CÉUS PROCLAMAM",
            "OS GUERREIROS SE PREPARAM",
            "OS QUE CONFIAM NO SENHOR",
            "OS SEGREDOS DO TEU CORAÇÃO",
            "OS SEUS CABELOS BRANCOS",
            "OS SINAIS DO FIM SE CUMPREM",
            "OS TEUS ANJOS TE EXALTAM ",
            "OUÇO A VOZ DO MEU AMADO ME CHAMAR",
            "OUÇO O CLAMOR DO BOM PASTOR",
            "OUÇO UMA VOZ TÃO SUAVE",
            "OUVE A VOZ DE JESUS",
            "OUVE, Ó DEUS",
            "OUVE, POIS, ISRAEL ",
            "OUVI COMO QUE A VOZ DE UMA GRANDE MULTIDÃO",
            "OUVI NO CÉU (BODAS DO CORDEIRO) ",
            "OUVI O SALVADOR DIZER",
            "OUVI, Ó CÉUS, E FALAREI",
            "PAI CELESTE",
            "PAI DE AMOR, GOSTO TANTO DE TI",
            "PAI, A TI ENTREGO O MEU ESPÍRITO",
            "PAI, ESTOU A TE CLAMAR",
            "PAI, TUA BELEZA ME ADMIRA",
            "PARA OS MONTES OLHAREI",
            "PARA QUEM IREMOS NÓS?",
            "PÁTRIA MINHA",
            "PEDRA DE ESQUINA",
            "PELA FÉ EU CAMINHO",
            "PELA FÉ EU POSSO CONTEMPLAR JESUS",
            "PELA FÉ SOMOS SALVOS",
            "PELAS PRAIAS GALILÉIAS VEM JESUS",
            "PELO SANGUE DE JESUS",
            "PELO SANGUE DE JESUS EU VOU CLAMAR ",
            "PELO SANGUE DE JESUS IREI CLAMAR",
            "PELO VALE ESCURO SEGUIREI JESUS",
            "PERDIDO FOI QUE ELE ME ENCONTROU",
            "PEREGRINANDO POR SOBRE OS MONTES",
            "PERFEITO AMOR EU CONHECI",
            "PÕE TEU SANGUE SOBRE MIM",
            "POR AMOR",
            "POR AMOR JESUS MORREU",
            "POR ONDE QUER QUE EU VÁ",
            "POR QUE DEIXAR QUE AS ÂNSIAS ",
            "POSSO SENTIR O SEU TOQUE EM MIM (GLORIFICA) ",
            "PRECIOSAS SÃO AS HORAS",
            "PRÍNCIPE DA PAZ",
            "PROCLAMAI A TODO O MUNDO ",
            "PROFUNDOS VALES EU TEREI DE PASSAR",
            "PROSTRADO ESTOU DIANTE DE TI",
            "PURIFICADO COM SANGUE ESTOU",
            "QUAL MADEIRA",
            "QUAL O ADORNO DESTA VIDA?",
            "QUANDO A ANGELICAL TROMBETA",
            "QUANDO A ANGÚSTIA VEM",
            "QUANDO A MÃO DE DEUS EM MIM VEIO TOCAR",
            "QUANDO A TEMPESTADE RUGE ",
            "QUANDO A TRISTEZA SURGIR",
            "QUANDO A ÚLTIMA TROMBETA ECOAR",
            "QUANDO ANDAVA NO MUNDO ESCRAVIZADO",
            "QUANDO AS LUTAS ME CERCAM",
            "QUANDO BUSCAMOS",
            "QUANDO DOBRO OS MEUS JOELHOS EM ORAÇÃO",
            "QUANDO FALO COM DEUS",
            "QUANDO ISRAEL SAIU DO EGITO",
            "QUANDO JESUS PROVOU O SEU AMOR POR MIM",
            "QUANDO JESUS SEU SANGUE VERTEU",
            "QUANDO JESUS UM DIA",
            "QUANDO LÁ DO CÉU DESCENDO",
            "QUANDO MAIS NINGUÉM TE COMPREENDE",
            "QUANDO MEU TEMPO DE LUTA PASSAR",
            "QUANDO O DIA AMANHECE",
            "QUANDO O JORDÃO PASSARMOS UNIDOS",
            "QUANDO O MUNDO AQUI DEIXAR",
            "QUANDO OS CÉUS ESTOU À CONTEMPLAR",
            "QUANDO PARECE QUE TUDO ACABOU",
            "QUANDO SERÁ O GRANDE DIA ",
            "QUANDO TE PROSTRARES",
            "QUANDO VEM NOS OLHOS UMA LÁGRIMA",
            "QUANTO MAIS EU TE CONHEÇO",
            "QUANTOS FIÉIS, SENHOR",
            "QUÃO AMÁVEIS SÃO",
            "QUÃO BONDOSO AMIGO É CRISTO",
            "QUÃO DIFÍCIL É, SENHOR (FAZE-ME UM VENCEDOR) ",
            "QUÃO DOCE E MEIGO É OUVIR",
            "QUE ALEGRIA",
            "QUE AS PALAVRAS DA MINHA BOCA",
            "QUE CALOR É ESTE EM VOLTA DO ALTAR ",
            "QUE CONSOLAÇÃO",
            "QUE DIA FELIZ",
            "QUE DOCE VOZ TEM MEU SENHOR",
            "QUE GRANDE REUNIÃO (JESUS DE NAZARÉ) ",
            "QUE IMPORTA",
            "QUE QUERES QUE EU TE FAÇA?",
            "QUE SEGURANÇA TENHO EM JESUS",
            "QUE VISTA AMÁVEL É (Salmo 132) ",
            "QUEM BEBER DA ÁGUA QUE EU LHE DER",
            "QUEM CANTAR AQUI SE ALEGRARÁ",
            "QUEM É COMO TU?",
            "QUEM É COMO TU?",
            "QUEM É ESTA QUE APARECE",
            "QUEM É QUE DÁ ÁGUA AO SEDENTO?",
            "QUEM ERA EU ANTES DE CONHECER",
            "QUEM IRÁ? (PRECIOSA SEMENTE)",
            "QUEM ME DÁ ÁGUA",
            "QUEM ME DERA",
            "QUEM SOU EU, SENHOR? ",
            "QUERES IR PRA GLÓRIA? ",
            "QUERES NESTE MUNDO SER UM VENCEDOR?",
            "QUERO ANDAR EM TEU CAMINHO, SENHOR",
            "QUERO ESTAR AO PÉ DA CRUZ",
            "QUERO PROSSEGUIR",
            "QUERO QUE ME TOQUES, SENHOR",
            "QUERO QUE VOCÊ CONHEÇA",
            "QUERO SER COMO DAVI",
            "QUERO SER FIEL AO MEU SENHOR",
            "QUERO SER UM VASO SE BÊNÇÃO",
            "QUERO TOCAR EM TUAS VESTES, SENHOR",
            "QUERO VIVER PARA SEMPRE COM JESUS",
            "REDENTOR ONIPOTENTE",
            "REGOZIJAI-VOS",
            "RESPLANDECE, Ó JERUSALÉM ",
            "REUNIMO-NOS AQUI PRA TE ADORAR",
            "REVELAÇÃO ABRE PRA VOCÊ",
            "REVESTE, SENHOR, TEU POVO",
            "ROCHA ETERNA",
            "ROCHA MINHA",
            "ROCHEDO FORTE É O SENHOR",
            "RUDE CRUZ",
            "SANTO É O QUE ESTÁ NO TRONO",
            "SANTO É SEU NOME",
            "SANTO, SANTO, SANTO É O SENHOR ",
            "SANTO, SANTO, SANTO, Ó DEUS DE GLÓRIA E PODER",
            "SANTO! SANTO! SANTO! DEUS ONIPOTENTE!",
            "SÃO DE JESUS AS HISTÓRIAS QUE EU QUERO OUVIR",
            "SAUDAI O NOME DE JESUS",
            "SE A FÉ POR VEZES FALTA",
            "SE A VIDA PARECE PESADA",
            "SE ANDA TRISTE O TEU VIVER",
            "SE ANDARMOS NA LUZ",
            "SE AS LUTAS DA VIDA",
            "SE CANSADO TU ESTÁS",
            "SE DEUS É POR NÓS",
            "SE DISPUSERES O TEU CORAÇÃO",
            "SE DISPUSERES O TEU CORAÇÃO (JÓ 11:13-19) ",
            "SE EM PROFUNDO ABISMO TE ENCONTRAS ",
            "SE EM TEU VIVER",
            "SE EM TUA VIDA FALTA PAZ",
            "SE EM TUA VIDA NÃO ENCONTRAS PAZ E LUZ",
            "SE ESTA NOITE DEUS PEDIR TUA ALMA",
            "SE ESTÁS CANSADO",
            "SE EU ESTIVESSE NA ALVORADA ",
            "SÊ EXALTADO, Ó DEUS",
            "SE HOJE ESCUTARES",
            "SE NÃO FOSSE O AMOR",
            "SE NÃO FOSSE O SENHOR",
            "SE NÃO PUDERES MAIS",
            "SE ORARMOS AO SENHOR",
            "SE PAZ, A MAIS DOCE",
            "SE TE ENCONTRARES TRISTE",
            "SE TU ESTÁS TÃO LONGE DO SENHOR",
            "SE TU PEDISTE UM SINAL ",
            "SE TU PROCURAS PELA PAZ",
            "SE UM DIA DEUS PROMETEU",
            "SE VOCÊ QUISER SABER",
            "SE, DA VIDA, AS VAGAS PROCELOSAS SÃO",
            "SEGUIR-TE-EI",
            "SEI QUE CRISTO VOLTARÁ",
            "SEI QUE NA CRUZ SEU SANGUE VERTEU",
            "SEI QUE O SENHOR",
            "SEI QUE SOU AMADO DO MEU SALVADOR",
            "SEI, SENHOR",
            "SEJA SÓ O SENHOR LOUVADO AQUI",
            "SEMPRE QUE QUISERES FALAREI CONTIGO ",
            "SEMPRE VOU LEMBRAR O QUE FIZESTE POR MIM ",
            "SENHOR, A TI CLAMO",
            "SENHOR, EU NEM SEI CONTAR",
            "SENHOR, EU QUERO DEPOSITAR",
            "SENHOR, EU QUERO SERVIR-TE",
            "SENHOR, GUIA-NOS",
            "SENHOR, MANDA PODER",
            "SENHOR, ME CHEGO A TI",
            "SENHOR, ME ENSINA",
            "SENHOR, MEU DEUS E PAI",
            "SENHOR, MEU DEUS, O QUE DIREI DE TI",
            "SENHOR, MEU DEUS, QUANDO EU MARAVILHADO",
            "SENHOR, O QUE É A NOSSA VIDA?",
            "SENHOR, OUVE A MINHA ORAÇÃO",
            "SENHOR, QUEM SÃO AQUELES ",
            "SENHOR, SE ESTIVESSES AQUI (LÁZARO) ",
            "SENHOR, SUPLICO A TI EM ORAÇÃO",
            "SENHOR, TE AMO, TE AMO",
            "SENHOR, TU ME SONDASTE E ME CONHECES",
            "SENTE EM TUA FACE O ROÇAR",
            "SEQUÊNCIA DE LOUVORES Nº 1",
            "SEQUÊNCIA DE LOUVORES Nº 2",
            "SEQUÊNCIA DE LOUVORES Nº 3",
            "SERÁ DE MANHÃ ",
            "SETE CASTIÇAIS",
            "SEU CORPO CANSADO PELAS CAMINHADAS",
            "SEU NOME É JESUS",
            "SEU NOME É MARAVILHOSO",
            "SÓ JESUS TE PODE DAR O QUE PROCURAS ",
            "SÓ O PODER DE DEUS",
            "SÓ TU ÉS, SENHOR",
            "SÓ TU NOS FAZES VENCEDORES ",
            "SÓ UMA VOZ ME BASTA",
            "SOMENTE PELA FÉ A OBRA DE DEUS",
            "SOMOS TEU POVO",
            "SOMOS TEU POVO E QUEREMOS",
            "SONDA-ME, Ó DEUS",
            "SONHEI COM JESUS ESTA NOITE",
            "SOU FELIZ COM JESUS",
            "SOU FORASTEIRO AQUI ",
            "SOU UM SOLDADO DO BOM SALVADOR",
            "SOU UMA CRIANÇA FELIZ",
            "SUBA A MINHA ORAÇÃO",
            "SUBINDO PARA O CÉU EU VOU ",
            "TAL QUAL ESTOU",
            "TANTO TEMPO JÁ FAZ QUE O CHAMADO DIVINAL",
            "TE ADORAMOS",
            "TE EXALTAREMOS",
            "TE LOUVAMOS, SENHOR ",
            "TE SUPLICO, Ó DEUS, EM ORAÇÃO",
            "TEM BOM ÂNIMO, POBRE PECADOR",
            "TEMEI A DEUS",
            "TENHO GRANDE GOZO",
            "TENHO LIDO DA BELA CIDADE",
            "TENHO NOVA VIDA",
            "TENHO SAUDADES DE JESUS, MEU MESTRE",
            "TENHO UM CORAÇÃO ALEGRE",
            "TENHO UM SENHOR MUITO FORTE",
            "TENHO UMA CANDEIA",
            "TENHO UMA PEDRA VIVA",
            "TENHO UMA SEMENTE",
            "TEU NOME É PRA MIM, SENHOR",
            "TEU POVO CLAMA",
            "TOCA PELA FÉ",
            "TODA A MINHA DOR JESUS LEVOU",
            "TODA A TERRA TE EXALTA",
            "TODA PROMESSA",
            "TODO LOUVOR SEJA DADO A DEUS",
            "TODO O MEU SER TE AMA",
            "TODO SER QUE TEM FÔLEGO",
            "TODOS OS POVOS",
            "TOMAI AGORA O PÃO",
            "TOTALMENTE DESEJÁVEL É MEU AMADO ",
            "TRANSBORDA-ME, SENHOR",
            "TU ÉS FIEL, SENHOR",
            "TU ÉS MEU REI",
            "TU ÉS O CRISTO, O FILHO DO DEUS VIVO ",
            "TU QUE ANDAS SÓ E TRISTE SEM SABER O CAMINHO",
            "TU QUE ESTÁS ASSENTADO",
            "TU QUE SOBRE A AMARGA CRUZ",
            "TU, Ó SENHOR (AVIVA A TUA OBRA)",
            "TUA GLÓRIA ENCHE TODA A TERRA",
            "TUA GRAÇA ME BASTA, Ó SENHOR ",
            "TUA MÃO É PODEROSA",
            "TUA, Ó DEUS, É TODA A GRANDEZA",
            "TUDO SE FEZ NOVO",
            "TUDO, Ó CRISTO, A TI ENTREGO",
            "UM CERTO PASTORZINHO",
            "UM CORPO SÓ, UM SÓ ESPÍRITO",
            "UM DIA A IGREJA SUBIRÁ",
            "UM DIA EU QUIS TE DEIXAR",
            "UM DIA JESUS ACHOU-ME",
            "UM DIA JESUS DESCEU DA SUA GLÓRIA",
            "UM MILAGRE É",
            "UM NOVO CÉU, UMA NOVA TERRA SE FARÁ",
            "UM NOVO LAR ME ESPERA",
            "UM PENDÃO REAL VOS ENTREGOU O REI",
            "UM POBRE CEGO",
            "UMA CENTELHA SÓ",
            "UMA CERTA VEZ, JESUS CRISTO",
            "UMA LUZ BRILHOU EM MEU CAMINHO",
            "UMA LUZ RESPLANDECENTE",
            "UMA OVELHINHA DE JESUS EU SOU",
            "UMA VOZ MANSA E DELICADA",
            "UMA VOZ ME DISSE LÁ DO CÉU",
            "VAI RAIAR O DIA",
            "VAMOS LAVAR AS VESTES",
            "VARÕES GALILEUS",
            "VEM PARA O MEIO",
            "VEM SOBRE MIM, ESPÍRITO DE DEUS",
            "VEM, AMADO MEU",
            "VEM, DERRAMA A PAZ",
            "VEM, ESPÍRITO DE DEUS",
            "VEM, JESUS CRISTO JÁ VEM",
            "VEM, Ó CRISTO, ENCHER MEU CÁLICE",
            "VEM, SENHOR, VISITA TUA VINHA",
            "VEM, VISITA TUA IGREJA",
            "VEM! MARANATA! JESUS VEM!",
            "VENCEDOR SEREI",
            "VENCER, VENCER",
            "VENHO, SENHOR, MINHA VIDA OFERECER",
            "VI UM NOVO CÉU",
            "VIGIAI E SEMPRE ORAI, Ó CRENTES",
            "VINDE, CANTAI E ENTOAI LOUVORES A JESUS",
            "VINDE, MENINOS",
            "VITÓRIA DEUS DARÁ A MIM, EU SEI",
            "VITÓRIA SOBRE VITÓRIA",
            "VIVER É TÃO LINDO",
            "VIVES MUITO ALÉM DO CÉU",
            "VIVI TÃO LONGE DO SENHOR",
            "VOCÊ NÃO ESTÁ SOZINHO",
            "VOCÊ SABE O QUE É SALVAÇÃO?",
            "VOU CAMINHANDO PRA JERUSALÉM",
            "VOU CLAMAR",
            "VOU CONTAR-VOS O QUE PENSO DO MEU MESTRE",
            "VOU GUIAR-TE A UMA RICA FONTE",
    "AQUILO QUE FUI NÃO SOU MAIS"};

    public static final String[] NUMANTIGO = {"6656",
            "6626",
            "6647",
            "6640",
            "-",
            "9991",
            "9949",
            "7788",
            "4421",
            "2298",
            "35",
            "6658",
            "2207",
            "2304",
            "4441",
            "2293",
            "4469",
            "2213",
            "9994",
            "8823",
            "1192",
            "4440",
            "1156",
            "-",
            "6610",
            "7780",
            "4470",
            "4466",
            "9946",
            "7773",
            "8803",
            "3326",
            "8838",
            "4413",
            "8843",
            "1126",
            "21",
            "2221",
            "6655",
            "6602",
            "9029",
            "3354",
            "1190",
            "-",
            "7703",
            "6625",
            "5561",
            "41",
            "5535",
            "-",
            "-",
            "2285",
            "7701",
            "4424",
            "2231",
            "7802",
            "5547",
            "6623",
            "7804",
            "6649",
            "-",
            "5569",
            "5568",
            "1133",
            "6634",
            "-",
            "46",
            "-",
            "4422",
            "4461",
            "5567",
            "-",
            "3387",
            "2255",
            "7795",
            "2219",
            "2307",
            "2243",
            "5504",
            "552",
            "579",
            "3341",
            "-",
            "7759",
            "3310",
            "554",
            "-",
            "-",
            "22",
            "7711",
            "7721",
            "7704",
            "3330",
            "5533",
            "5560",
            "558",
            "-",
            "2200",
            "8842",
            "3304",
            "576",
            "8831",
            "8841",
            "3393",
            "9959",
            "7709",
            "5576",
            "4408",
            "4407",
            "6613",
            "6651",
            "2223",
            "6630",
            "-",
            "3355",
            "7712",
            "549",
            "5512",
            "1117",
            "8844",
            "5506",
            "6600",
            "4476",
            "5",
            "15",
            "3",
            "9904",
            "9903",
            "-",
            "9909",
            "-",
            "7805",
            "2287",
            "8827",
            "550",
            "4449",
            "2222",
            "-",
            "9930",
            "2303",
            "6601",
            "5517",
            "4420",
            "1168",
            "9980",
            "-",
            "3359",
            "44",
            "9951",
            "3340",
            "8837",
            "27",
            "7769",
            "1113",
            "9920",
            "1115",
            "1170",
            "8805",
            "2274",
            "9952",
            "2228",
            "9941",
            "2264",
            "9924",
            "4450",
            "7801",
            "2268",
            "3372",
            "-",
            "9933",
            "5522",
            "9958",
            "2259",
            "2270",
            "36",
            "7803",
            "5582",
            "3385",
            "6646",
            "9935",
            "4400",
            "3300",
            "7766",
            "560",
            "8820",
            "1143",
            "3371",
            "1119",
            "3362",
            "4414",
            "4459",
            "1110",
            "2294",
            "4464",
            "7",
            "-",
            "1108",
            "1175",
            "9013",
            "3346",
            "2205",
            "7763",
            "6641",
            "3338",
            "-",
            "3380",
            "3379",
            "1107",
            "1112",
            "577",
            "567",
            "1169",
            "573",
            "3333",
            "9005",
            "9923",
            "9007",
            "1138",
            "1109",
            "3383",
            "3352",
            "-",
            "2257",
            "6659",
            "4465",
            "7770",
            "3350",
            "8830",
            "5509",
            "9905",
            "1116",
            "9955",
            "7806",
            "2282",
            "9914",
            "8814",
            "9942",
            "2262",
            "566",
            "9940",
            "9023",
            "4479",
            "47",
            "7784",
            "3342",
            "4428",
            "1141",
            "24",
            "3314",
            "-",
            "-",
            "1125",
            "7775",
            "9971",
            "4427",
            "9025",
            "-",
            "9932",
            "2276",
            "7790",
            "1162",
            "5515",
            "9944",
            "5514",
            "5516",
            "5513",
            "5570",
            "5534",
            "551",
            "3302",
            "2248",
            "3360",
            "7777",
            "14",
            "581",
            "2302",
            "17",
            "3325",
            "9996",
            "2300",
            "-",
            "9937",
            "1132",
            "4417",
            "6670",
            "580",
            "1128",
            "2278",
            "1167",
            "6629",
            "7715",
            "4448",
            "52",
            "3390",
            "3364",
            "3365",
            "4455",
            "4460",
            "8828",
            "9960",
            "5539",
            "-",
            "2249",
            "6654",
            "2218",
            "2250",
            "7761",
            "7814",
            "2236",
            "8822",
            "9018",
            "3356",
            "9919",
            "5554",
            "-",
            "1149",
            "5503",
            "2245",
            "8821",
            "2203",
            "33",
            "3337",
            "7776",
            "5555",
            "-",
            "9985",
            "9974",
            "6657",
            "-",
            "7800",
            "9945",
            "4419",
            "5528",
            "-",
            "4409",
            "2277",
            "2253",
            "3334",
            "2288",
            "9907",
            "6616",
            "2247",
            "8809",
            "8808",
            "9922",
            "6676",
            "6652",
            "8824",
            "4426",
            "9016",
            "9027",
            "6620",
            "9002",
            "2263",
            "5548",
            "9921",
            "4412",
            "3368",
            "9950",
            "2240",
            "2242",
            "5562",
            "3363",
            "9010",
            "4454",
            "6617",
            "1134",
            "6605",
            "6624",
            "8807",
            "6669",
            "2220",
            "-",
            "575",
            "7707",
            "7705",
            "9947",
            "-",
            "2279",
            "-",
            "3348",
            "1194",
            "3305",
            "2252",
            "3336",
            "3332",
            "4453",
            "5551",
            "5564",
            "6621",
            "4437",
            "4463",
            "2272",
            "6631",
            "1101",
            "9962",
            "9017",
            "4416",
            "4438",
            "12",
            "54",
            "9961",
            "9966",
            "6606",
            "-",
            "2301",
            "9957",
            "9981",
            "5510",
            "4477",
            "557",
            "9019",
            "2212",
            "1147",
            "-",
            "2244",
            "5542",
            "-",
            "9972",
            "7807",
            "7808",
            "9001",
            "5557",
            "5581",
            "9973",
            "2229",
            "7789",
            "5536",
            "1179",
            "6644",
            "3392",
            "1129",
            "8815",
            "9917",
            "1180",
            "8833",
            "5571",
            "2266",
            "-",
            "1104",
            "1102",
            "1187",
            "9934",
            "6622",
            "1106",
            "9000",
            "6673",
            "-",
            "9997",
            "2217",
            "3394",
            "2261",
            "1124",
            "6615",
            "6612",
            "2225",
            "2275",
            "6",
            "4425",
            "9939",
            "4423",
            "2306",
            "5521",
            "6633",
            "6632",
            "39",
            "9030",
            "31",
            "5565",
            "7757",
            "-",
            "5549",
            "8835",
            "562",
            "9969",
            "-",
            "9021",
            "1174",
            "7702",
            "5552",
            "-",
            "6666",
            "6671",
            "7714",
            "7719",
            "7706",
            "7811",
            "-",
            "6636",
            "6648",
            "4462",
            "2269",
            "3329",
            "578",
            "6628",
            "8819",
            "1139",
            "9979",
            "2283",
            "2206",
            "5575",
            "7710",
            "3312",
            "-",
            "3319",
            "1145",
            "9910",
            "9906",
            "2237",
            "1161",
            "-",
            "4433",
            "9901",
            "6675",
            "1123",
            "7768",
            "3375",
            "5559",
            "4436",
            "-",
            "1103",
            "6674",
            "6667",
            "7771",
            "9992",
            "9995",
            "7778",
            "6627",
            "49",
            "5583",
            "5577",
            "7809",
            "7716",
            "3347",
            "2295",
            "1122",
            "3382",
            "8810",
            "1163",
            "9913",
            "7774",
            "2254",
            "5518",
            "1181",
            "3386",
            "5543",
            "7753",
            "5520",
            "2258",
            "5574",
            "9915",
            "3303",
            "-",
            "-",
            "37",
            "570",
            "9953",
            "8811",
            "8836",
            "9015",
            "7752",
            "9926",
            "9986",
            "7750",
            "4471",
            "556",
            "5546",
            "45",
            "6609",
            "9970",
            "6661",
            "8834",
            "-",
            "9022",
            "6638",
            "7787",
            "9987",
            "1185",
            "8829",
            "2284",
            "7754",
            "2256",
            "2289",
            "563",
            "1184",
            "8832",
            "51",
            "6639",
            "4478",
            "2297",
            "9993",
            "5525",
            "4457",
            "3313",
            "-",
            "6614",
            "-",
            "8839",
            "6619",
            "4480",
            "3349",
            "4443",
            "5537",
            "7713",
            "6650",
            "6637",
            "-",
            "7751",
            "7772",
            "4442",
            "28",
            "2215",
            "6618",
            "5519",
            "3322",
            "-",
            "3344",
            "50",
            "1",
            "2",
            "32",
            "53",
            "4430",
            "1186",
            "3311",
            "3378",
            "3376",
            "3377",
            "-",
            "-",
            "7717",
            "7764",
            "2224",
            "1130",
            "5531",
            "20",
            "2271",
            "4458",
            "5573",
            "7779",
            "7700",
            "6660",
            "5566",
            "3318",
            "5572",
            "4446",
            "2214",
            "1173",
            "30",
            "40",
            "5556",
            "1160",
            "1127",
            "2201",
            "9912",
            "9026",
            "9003",
            "7718",
            "9928",
            "5532",
            "7708",
            "3315",
            "3358",
            "4404",
            "5529",
            "5505",
            "-",
            "4451",
            "9943",
            "5523",
            "1140",
            "3339",
            "7767",
            "7782",
            "-",
            "7810",
            "4432",
            "9918",
            "6611",
            "1105",
            "9902",
            "9012",
            "3351",
            "1178",
            "5579",
            "2280",
            "2234",
            "2299",
            "2210",
            "4435",
            "8",
            "-",
            "38",
            "3316",
            "2209",
            "2233",
            "7793",
            "13",
            "1121",
            "1120",
            "1150",
            "8840",
            "-",
            "564",
            "9954",
            "-",
            "3317",
            "18",
            "9900",
            "4418",
            "4402",
            "5541",
            "3328",
            "2238",
            "-",
            "3307",
            "5540",
            "2211",
            "3384",
            "34",
            "4473",
            "9948",
            "2290",
            "7797",
            "1177",
            "2292",
            "5526",
            "3391",
            "3374",
            "559",
            "5563",
            "5558",
            "7798",
            "3306",
            "-",
            "4",
            "3327",
            "4475",
            "4482",
            "7720",
            "3331",
            "-",
            "7755",
            "6663",
            "4415",
            "8818",
            "3353",
            "5544",
            "2251",
            "7813",
            "3323",
            "9975",
            "2246",
            "4444",
            "1136",
            "8826",
            "7799",
            "7799",
            "5538",
            "3388",
            "2204",
            "9977",
            "1135",
            "5502",
            "-",
            "1172",
            "3370",
            "7796",
            "1193",
            "2235",
            "4472",
            "1171",
            "9982",
            "4410",
            "4434",
            "1183",
            "9009",
            "2305",
            "5553",
            "-",
            "6604",
            "9989",
            "11",
            "1191",
            "3357",
            "3381",
            "1114",
            "6635",
            "6662",
            "-",
            "6645",
            "6643",
            "9927",
            "6664",
            "3361",
            "3308",
            "1152",
            "16",
            "3389",
            "1144",
            "3343",
            "1158",
            "1157",
            "3324",
            "1151",
            "1154",
            "1188",
            "1146",
            "8806",
            "5550",
            "6665",
            "3335",
            "2260",
            "3367",
            "3309",
            "553",
            "7765",
            "3345",
            "1165",
            "1182",
            "1155",
            "7794",
            "1153",
            "3321",
            "2232",
            "9967",
            "9014",
            "5524",
            "9028",
            "568",
            "26",
            "-",
            "2296",
            "25",
            "6608",
            "6607",
            "4468",
            "4467",
            "8817",
            "9",
            "3366",
            "55",
            "4474",
            "6642",
            "4406",
            "23",
            "-",
            "-",
            "42",
            "2291",
            "7758",
            "569",
            "8800",
            "8801",
            "8802",
            "-",
            "5508",
            "1100",
            "8804",
            "9911",
            "1131",
            "2226",
            "4405",
            "-",
            "3320",
            "8825",
            "1118",
            "4439",
            "4403",
            "9916",
            "2239",
            "4431",
            "9925",
            "9938",
            "555",
            "8845",
            "7756",
            "1142",
            "6603",
            "6668",
            "-",
            "9020",
            "9024",
            "5507",
            "2241",
            "5578",
            "2227",
            "5527",
            "9988",
            "9976",
            "9983",
            "2281",
            "9931",
            "7785",
            "19",
            "561",
            "3301",
            "6672",
            "5500",
            "7792",
            "7783",
            "9965",
            "1176",
            "4452",
            "2273",
            "29",
            "2286",
            "3369",
            "9999",
            "7760",
            "5530",
            "1166",
            "4481",
            "7781",
            "-",
            "9956",
            "7812",
            "1164",
            "2230",
            "9908",
            "4445",
            "9978",
            "7786",
            "2202",
            "1111",
            "1189",
            "9011",
            "5545",
            "4429",
            "7762",
            "1148",
            "2265",
            "2216",
            "9968",
            "9008",
            "572",
            "4411",
            "9004",
            "10",
            "9964",
            "9984",
            "4456",
            "565",
            "6653",
            "8816",
            "7791",
            "4447",
            "4483",
            "571",
            "5580",
            "8812",
            "3373",
            "4401",
            "5501",
            "5511",
            "48",
            "9936",
            "8813",
            "9929",
            "9963",
            "574",
            "2208",
            "1159",
            "9990",
            "9006",
            "43",
            "2267",
            "1137",
    "CONTRA-CAPA"};

    public static final String[] NUMNOVO = {"622",
            "593",
            "614",
            "607",
            "722",
            "-",
            "-",
            "682",
            "402",
            "641",
            "35",
            "624",
            "103",
            "183",
            "422",
            "174",
            "449",
            "109",
            "-",
            "753",
            "278",
            "421",
            "251",
            "717",
            "-",
            "677",
            "450",
            "446",
            "-",
            "559",
            "734",
            "316",
            "768",
            "396",
            "773",
            "779",
            "-",
            "116",
            "621",
            "574",
            "646",
            "-",
            "276",
            "475",
            "653",
            "592",
            "535",
            "41",
            "510",
            "379",
            "293",
            "167",
            "651",
            "405",
            "122",
            "689",
            "521",
            "590",
            "691",
            "616",
            "712",
            "543",
            "542",
            "229",
            "601",
            "292",
            "46",
            "790",
            "403",
            "787",
            "541",
            "720",
            "366",
            "140",
            "193",
            "114",
            "701",
            "131",
            "481",
            "58",
            "84",
            "329",
            "719",
            "288",
            "304",
            "60",
            "384",
            "94",
            "22",
            "-",
            "665",
            "-",
            "320",
            "508",
            "534",
            "64",
            "95",
            "97",
            "772",
            "-",
            "82",
            "761",
            "771",
            "-",
            "-",
            "784",
            "550",
            "391",
            "390",
            "582",
            "618",
            "780",
            "597",
            "713",
            "469",
            "659",
            "776",
            "488",
            "215",
            "774",
            "483",
            "572",
            "456",
            "5",
            "15",
            "3",
            "-",
            "-",
            "96",
            "-",
            "714",
            "692",
            "169",
            "757",
            "777",
            "430",
            "117",
            "199",
            "-",
            "182",
            "573",
            "493",
            "401",
            "259",
            "-",
            "378",
            "344",
            "44",
            "-",
            "328",
            "767",
            "27",
            "645",
            "211",
            "-",
            "213",
            "261",
            "736",
            "157",
            "-",
            "-",
            "-",
            "147",
            "-",
            "431",
            "-",
            "151",
            "354",
            "723",
            "-",
            "498",
            "-",
            "142",
            "153",
            "36",
            "690",
            "555",
            "364",
            "613",
            "-",
            "88",
            "295",
            "89",
            "66",
            "750",
            "239",
            "353",
            "217",
            "-",
            "189",
            "440",
            "-",
            "175",
            "444",
            "-",
            "706",
            "208",
            "-",
            "-",
            "334",
            "-",
            "669",
            "608",
            "327",
            "377",
            "359",
            "-",
            "207",
            "-",
            "778",
            "73",
            "260",
            "79",
            "323",
            "-",
            "-",
            "-",
            "234",
            "209",
            "362",
            "340",
            "715",
            "-",
            "625",
            "445",
            "564",
            "338",
            "760",
            "486",
            "-",
            "214",
            "-",
            "693",
            "164",
            "-",
            "745",
            "-",
            "145",
            "72",
            "-",
            "-",
            "459",
            "47",
            "679",
            "330",
            "409",
            "237",
            "24",
            "466",
            "724",
            "727",
            "222",
            "560",
            "-",
            "408",
            "-",
            "198",
            "-",
            "159",
            "684",
            "-",
            "491",
            "-",
            "490",
            "492",
            "489",
            "544",
            "509",
            "57",
            "297",
            "135",
            "345",
            "642",
            "14",
            "86",
            "181",
            "17",
            "90",
            "-",
            "180",
            "716",
            "-",
            "228",
            "398",
            "635",
            "85",
            "224",
            "161",
            "-",
            "596",
            "661",
            "429",
            "52",
            "368",
            "348",
            "-",
            "436",
            "441",
            "758",
            "-",
            "514",
            "476",
            "136",
            "620",
            "557",
            "281",
            "289",
            "700",
            "127",
            "752",
            "-",
            "785",
            "-",
            "528",
            "707",
            "244",
            "480",
            "133",
            "751",
            "100",
            "33",
            "326",
            "674",
            "529",
            "725",
            "-",
            "-",
            "623",
            "791",
            "191",
            "-",
            "400",
            "504",
            "200",
            "392",
            "160",
            "-",
            "324",
            "170",
            "-",
            "584",
            "-",
            "740",
            "739",
            "-",
            "-",
            "-",
            "754",
            "407",
            "-",
            "-",
            "-",
            "-",
            "146",
            "522",
            "-",
            "395",
            "350",
            "-",
            "129",
            "783",
            "536",
            "347",
            "-",
            "435",
            "585",
            "230",
            "577",
            "591",
            "738",
            "634",
            "115",
            "195",
            "81",
            "656",
            "654",
            "-",
            "705",
            "162",
            "718",
            "336",
            "280",
            "299",
            "138",
            "468",
            "322",
            "434",
            "525",
            "538",
            "588",
            "418",
            "443",
            "155",
            "598",
            "202",
            "-",
            "-",
            "397",
            "419",
            "12",
            "54",
            "-",
            "-",
            "578",
            "197",
            "-",
            "-",
            "-",
            "788",
            "456",
            "63",
            "-",
            "108",
            "243",
            "382",
            "132",
            "517",
            "570",
            "-",
            "694",
            "695",
            "-",
            "531",
            "534",
            "-",
            "120",
            "683",
            "511",
            "-",
            "611",
            "370",
            "225",
            "746",
            "-",
            "268",
            "763",
            "545",
            "149",
            "294",
            "205",
            "203",
            "794",
            "-",
            "589",
            "-",
            "-",
            "638",
            "569",
            "-",
            "113",
            "91",
            "144",
            "221",
            "-",
            "192",
            "119",
            "158",
            "6",
            "406",
            "-",
            "404",
            "185",
            "497",
            "600",
            "599",
            "39",
            "-",
            "31",
            "539",
            "667",
            "565",
            "523",
            "765",
            "68",
            "-",
            "383",
            "-",
            "265",
            "652",
            "526",
            "93",
            "-",
            "636",
            "-",
            "663",
            "655",
            "644",
            "792",
            "603",
            "615",
            "442",
            "152",
            "319",
            "83",
            "595",
            "749",
            "235",
            "-",
            "165",
            "102",
            "549",
            "658",
            "306",
            "793",
            "310",
            "241",
            "-",
            "-",
            "-",
            "255",
            "381",
            "414",
            "-",
            "640",
            "87",
            "672",
            "187",
            "533",
            "417",
            "473",
            "204",
            "639",
            "632",
            "372",
            "-",
            "-",
            "675",
            "594",
            "49",
            "556",
            "789",
            "696",
            "-",
            "335",
            "176",
            "220",
            "361",
            "741",
            "256",
            "-",
            "563",
            "139",
            "494",
            "269",
            "365",
            "518",
            "287",
            "496",
            "-",
            "548",
            "-",
            "298",
            "21",
            "7",
            "37",
            "76",
            "-",
            "742",
            "766",
            "-",
            "470",
            "-",
            "-",
            "-",
            "451",
            "62",
            "520",
            "45",
            "580",
            "-",
            "627",
            "764",
            "728",
            "-",
            "605",
            "681",
            "-",
            "272",
            "759",
            "166",
            "284",
            "141",
            "171",
            "69",
            "271",
            "762",
            "51",
            "606",
            "458",
            "178",
            "-",
            "501",
            "438",
            "465",
            "196",
            "583",
            "571",
            "769",
            "587",
            "460",
            "337",
            "424",
            "512",
            "660",
            "617",
            "604",
            "710",
            "283",
            "673",
            "423",
            "28",
            "111",
            "586",
            "495",
            "313",
            "290",
            "332",
            "50",
            "1",
            "2",
            "32",
            "53",
            "411",
            "273",
            "305",
            "358",
            "356",
            "357",
            "648",
            "566",
            "-",
            "376",
            "118",
            "226",
            "507",
            "20",
            "154",
            "439",
            "547",
            "676",
            "650",
            "626",
            "540",
            "309",
            "546",
            "427",
            "110",
            "264",
            "30",
            "40",
            "530",
            "254",
            "223",
            "98",
            "-",
            "-",
            "-",
            "662",
            "-",
            "702",
            "657",
            "467",
            "343",
            "375",
            "505",
            "482",
            "729",
            "432",
            "-",
            "499",
            "236",
            "-",
            "671",
            "561",
            "708",
            "697",
            "413",
            "92",
            "581",
            "206",
            "-",
            "-",
            "339",
            "186",
            "552",
            "-",
            "125",
            "179",
            "106",
            "416",
            "8",
            "48",
            "38",
            "307",
            "105",
            "124",
            "685",
            "13",
            "219",
            "218",
            "245",
            "770",
            "380",
            "70",
            "-",
            "721",
            "308",
            "18",
            "-",
            "399",
            "386",
            "516",
            "318",
            "128",
            "726",
            "301",
            "515",
            "107",
            "363",
            "34",
            "453",
            "-",
            "-",
            "686",
            "267",
            "173",
            "502",
            "369",
            "562",
            "65",
            "537",
            "532",
            "-",
            "300",
            "567",
            "4",
            "317",
            "455",
            "462",
            "664",
            "321",
            "385",
            "-",
            "629",
            "786",
            "748",
            "341",
            "-",
            "137",
            "699",
            "314",
            "-",
            "134",
            "425",
            "232",
            "756",
            "687",
            "688",
            "513",
            "282",
            "101",
            "-",
            "231",
            "479",
            "474",
            "263",
            "352",
            "194",
            "279",
            "126",
            "452",
            "262",
            "-",
            "393",
            "415",
            "374",
            "-",
            "184",
            "527",
            "709",
            "576",
            "-",
            "11",
            "277",
            "342",
            "360",
            "212",
            "602",
            "628",
            "647",
            "612",
            "610",
            "-",
            "630",
            "346",
            "302",
            "247",
            "16",
            "367",
            "240",
            "331",
            "253",
            "252",
            "315",
            "246",
            "249",
            "274",
            "242",
            "737",
            "524",
            "631",
            "325",
            "143",
            "349",
            "303",
            "59",
            "670",
            "333",
            "258",
            "270",
            "250",
            "373",
            "248",
            "312",
            "123",
            "-",
            "-",
            "500",
            "-",
            "74",
            "26",
            "291",
            "177",
            "25",
            "579",
            "-",
            "448",
            "447",
            "747",
            "9",
            "-",
            "55",
            "454",
            "609",
            "389",
            "23",
            "568",
            "704",
            "42",
            "172",
            "-",
            "75",
            "731",
            "732",
            "733",
            "703",
            "485",
            "201",
            "735",
            "-",
            "227",
            "781",
            "388",
            "730",
            "311",
            "755",
            "216",
            "420",
            "387",
            "-",
            "-",
            "412",
            "-",
            "-",
            "61",
            "775",
            "666",
            "238",
            "575",
            "633",
            "649",
            "-",
            "-",
            "484",
            "130",
            "551",
            "782",
            "503",
            "-",
            "-",
            "-",
            "163",
            "-",
            "680",
            "19",
            "67",
            "296",
            "637",
            "371",
            "643",
            "190",
            "-",
            "266",
            "433",
            "156",
            "29",
            "168",
            "351",
            "-",
            "285",
            "506",
            "464",
            "461",
            "678",
            "711",
            "-",
            "698",
            "257",
            "121",
            "-",
            "426",
            "-",
            "286",
            "99",
            "210",
            "275",
            "-",
            "519",
            "410",
            "668",
            "-",
            "148",
            "112",
            "-",
            "-",
            "78",
            "394",
            "-",
            "10",
            "-",
            "-",
            "437",
            "71",
            "619",
            "471",
            "558",
            "428",
            "463",
            "77",
            "553",
            "743",
            "355",
            "188",
            "478",
            "487",
            "472",
            "-",
            "744",
            "56",
            "-",
            "80",
            "104",
            "-",
            "-",
            "-",
            "43",
            "150",
            "233",
    "CONTRA-CAPA"};
}
